=== openownership/data-standard/schema/entity-statement.json
{
  "id": "entity-statement.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "0.1",
  "title": "Entity statement",
  "description": "A statement identifying and describing the entity that is the subject of the ownership or control described in an ownership or control statement.",
  "type": "object",
  "properties": {
    "statementID": {
      "$ref": "components.json#/definitions/ID",
      "propertyOrder": 1
    },
    "statementType": {
      "title": "Statement type",
      "description": " This should always be 'entityStatement.",
      "type": "string",
      "enum": [
        "entityStatement"
      ],
      "propertyOrder": 2
    },
    "statementDate": {
      "$ref": "components.json#/definitions/StatementDate",
      "propertyOrder": 3
    },
    "isComponent": {
      "title": "Is component",
      "description": "Does this Entity Statement represent a component of an indirect ownership-or-control relationship? Where `isComponent` is 'true': (1) the `statementID` of this Entity Statement MUST be an element in the `componentStatementIDs` array of that primary Ownership-or-control Statement, (2) this Entity Statement MUST come before that primary Ownership-or-control Statement in a BODS package or stream, (3) the replacement of this Entity Statement SHOULD be considered when replacing the primary Ownership-or-control Statement. The primary Ownership-or-control Statement MUST have a `isComponent` value of 'false'.",
      "type": "boolean"
    },
    "entityType": {
      "title": "Type",
      "description": "From the entityType codelist. What kind of entity is this? The 'registeredEntity' code covers any legal entity created through an act of official registration, usually resulting in an identifier being assigned to the entity. The 'legalEntity' code covers other bodies with distinct legal personality (government departments, international institutions etc.).  The 'arrangement' code covers artificial entities, described in the data model for the purpose of associating one or more natural or legal persons together in an ownership or control relationship, but without implying that the parties to this arrangement have any other form of collective legal identity.",
      "type": "string",
      "enum": [
        "registeredEntity",
        "legalEntity",
        "arrangement",
        "anonymousEntity",
        "unknownEntity"
      ],
      "codelist": "entityType.csv",
      "openCodelist": false,
      "propertyOrder": 4
    },
    "unspecifiedEntityDetails": {
      "title": "Unspecified entity details",
      "description": "An explanation of why this entity has an `entityType` of 'anonymousEntity' or 'unknownEntity'. A `reason` MUST be specified.",
      "type": "object",
      "properties": {
        "reason": {
          "title": "Reason",
          "description": "The reason that an entity cannot be specified. From the unspecifiedReason codelist.",
          "type": "string",
          "enum": [
            "no-beneficial-owners",
            "subject-unable-to-confirm-or-identify-beneficial-owner",
            "interested-party-has-not-provided-information",
            "subject-exempt-from-disclosure",
            "interested-party-exempt-from-disclosure",
            "information-unknown-to-publisher",
            "unknown"
          ],
          "codelist": "unspecifiedReason.csv",
          "openCodelist": false
        },
        "description": {
          "title": "Description",
          "description": "Any supporting information about the absence of a specific entity. This field may be used to provide set phrases from a source system, or for a free-text explanation.",
          "type": "string"
        }
      },
      "required": [
        "reason"
      ],
      "propertyOrder": 5
    },
    "name": {
      "title": "Entity name",
      "description": "The declared name of this entity.",
      "type": "string",
      "propertyOrder": 6
    },
    "alternateNames": {
      "title": "Alternative names",
      "description": "An array of other names this entity is known by.",
      "type": "array",
      "items":{
        "type":"string",
        "title":"Name",
        "description":"A name this entity is known by."
      },
      "propertyOrder": 7
    },
    "incorporatedInJurisdiction": {
      "title": "Incorporated In Jurisdiction",
      "description": "Details on where this legal entity is incorporated",
      "$ref": "components.json#/definitions/Jurisdiction",
      "propertyOrder": 10
    },
    "identifiers": {
      "title": "Identifiers",
      "description": "One or more official identifiers for this entity. Where available, official registration numbers should be provided.",
      "type": "array",
      "items": {
        "$ref": "components.json#/definitions/Identifier"
      },
      "propertyOrder": 20
    },
    "foundingDate": {
      "title": "Founding date",
      "description": "When was this entity founded, created or registered. Please provide as precise a date as possible in ISO 8601 format. When only the year or year and month is known, these can be given as YYYY or YYYY-MM.",
      "type": "string",
      "pattern": "^([\\+-]?\\d{4}(?!\\d{2}\b))((-?)((0[1-9]|1[0-2])(\\3([12]\\d|0[1-9]|3[01]))?|W([0-4]\\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6])))([T\\s]((([01]\\d|2[0-3])((:?)[0-5]\\d)?|24\\:?00)([\\.,]\\d+(?!:))?)?(\\17[0-5]\\d([\\.,]\\d+)?)?([zZ]|([\\+-])([01]\\d|2[0-3]):?([0-5]\\d)?)?)?)?$",
      "propertyOrder": 30
    },
    "dissolutionDate": {
      "title": "Dissolution date",
      "description": "If this entity is no longer active, provide the date on which it was disolved or ceased. Please provide as precise a date as possible in ISO 8601 format. When only the year or year and month is known, these can be given as YYYY or YYYY-MM.",
      "type": "string",
      "pattern": "^([\\+-]?\\d{4}(?!\\d{2}\b))((-?)((0[1-9]|1[0-2])(\\3([12]\\d|0[1-9]|3[01]))?|W([0-4]\\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6])))([T\\s]((([01]\\d|2[0-3])((:?)[0-5]\\d)?|24\\:?00)([\\.,]\\d+(?!:))?)?(\\17[0-5]\\d([\\.,]\\d+)?)?([zZ]|([\\+-])([01]\\d|2[0-3]):?([0-5]\\d)?)?)?)?$",
      "propertyOrder": 35
    },
    "addresses": {
      "title": "Addresses",
      "description": "One or more addresses for this entity.",
      "type": "array",
      "items": {
        "$ref": "components.json#/definitions/Address"
      },
      "propertyOrder": 40
    },
    "uri": {
      "title": "URI",
      "description": "Where a [persistent URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) is available for this entity this should be included.",
      "type": "string",
      "format": "uri",
      "propertyOrder": 21
    },
    "replacesStatements": {
      "$ref": "components.json#/definitions/ReplacesStatements",
      "propertyOrder": 100
    },
    "publicationDetails": {
      "title": "Publication details",
      "description": "Information concerning the original publication of this statement.",
      "$ref": "components.json#/definitions/PublicationDetails",
      "propertyOrder":85
    },
    "source": {
      "title": "Source",
      "description": "The source of information about this entity, or of information that supports an anonymous or unknown entity statement.",
      "$ref": "components.json#/definitions/Source",
      "propertyOrder":89
    },
    "annotations": {
      "title": "Annotations",
      "description": "Annotations about this statement or parts of this statement",
      "type": "array",
      "items": {
        "$ref": "components.json#/definitions/Annotation"
      },
      "propertyOrder": 90
    }
  },
  "required": [
    "statementID",
    "statementType",
    "isComponent",
    "entityType",
    "publicationDetails"
  ]
}

=== openownership/data-standard/examples/workshop/modelling-bods-data/ren-consulting-limited.json
{
  "statementID": "3ff64336-9d26-49da-b0ce-f4685c6af139",
  "statementType": "entityStatement",
  "entityType": "registeredEntity",
  "isComponent": false,
  "name": "REN Consulting Limited",
  "identifiers": [
    {
      "scheme": "XE-KS-SRC",
      "id": "93821344"
    }
  ],
  "publicationDetails": {
    "publicationDate": "2017-12-01",
    "bodsVersion": "0.2",
    "publisher": {
      "name": "XXXXXXXXX"
    }
  }
}

=== openownership/data-standard/tests/data/entity-statement/valid/valid-entity-statement-loose-validation.json
{
    "statementID":"1dc0e987-5c57-4a1c-b3ad-61353b66a9b7",
    "statementType":"entityStatement",
    "isComponent": false,
    "statementDate":"2016-06-30",
    "entityType":"registeredEntity",
    "name":"Ibrakom Fzco",
    "incorporatedInJurisdiction":{
       "name":"UAE"
    },
    "identifiers":[
      {
        "id":"00335",
        "schemeName":"Jebel Ali Free Zone"
      }
    ],
    "publicationDetails": {
        "publicationDate": "2016-07-01",
        "bodsVersion": "0.2",
        "publisher": {
            "name": "Ibrakom Fzco"
        }
    }
  }

=== openownership/data-standard/tests/data/entity-statement/valid/valid-entity-statement-with-source.json
{
  "statementID": "323591c5-2093-4716-8494-c5573c7452e6",
  "statementType": "entityStatement",
  "isComponent": false,
  "statementDate": "2018-11-14",
  "entityType": "registeredEntity",
  "name": "OPEN DATA SERVICES CO-OPERATIVE LIMITED",
  "foundingDate": "2015-04-24",
  "identifiers": [
    {
      "scheme": "GB-COH",
      "id": "09506232"
    }
  ],
  "incorporatedInJurisdiction": {
    "code": "GB"
  },
  "source": {
    "type": ["officialRegister"],
    "description": "Companies House, United Kingdom",
    "url": "https://beta.companieshouse.gov.uk/company/09506232",
    "assertedBy": [
      {
      "name": "OPEN DATA SERVICES CO-OPERATIVE LIMITED"
      }
    ],
    "retrievedAt": "2018-11-14T17:23:43.977Z"
  },
  "publicationDetails": {
    "publicationDate": "2019-01-05",
    "bodsVersion": "0.2",
    "publisher": {
      "url": "http://example.com/"
    }
  }
}

=== openownership/data-standard/examples/workshop/modelling-bods-data/renco-holding-company-limited.json
{
  "statementID": "4dc0d9ba-ab30-42e2-b4c5-b895bacc59f5",
  "statementType": "entityStatement",
  "entityType": "registeredEntity",
  "isComponent": false,
  "name": "RENCO Holding Company",
  "identifiers": [
    {
      "scheme": "XE-LO-COH",
      "id": "28367095"
    }
  ],
  "publicationDetails": {
    "publicationDate": "2017-12-01",
    "bodsVersion": "0.2",
    "publisher": {
      "name": "XXXXXXXXX"
    }
  }
}

=== openownership/data-standard/tests/data/entity-statement/valid/valid-entity-statement-transliteration-annotations.json
{
  "statementID": "118e9402-054e-4f6f-bfb0-8e4e9bfe3756",
  "statementType": "entityStatement",
  "isComponent": false,
  "entityType": "registeredEntity",
  "name": "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ 'НАУКОВО-ВИРОБНИЧА ФІРМА 'MARCH-A''",
  "identifiers": [
    {
      "scheme": "UA-EDR",
      "id": "21505721"
    }
  ],
  "addresses": [
    {
      "address": "01021, м.Київ, Печерський район, ВУЛИЦЯ М.ГРУШЕВСЬКОГО, будинок 28/2, нежиле приміщення 43"
    }
  ],
  "annotations": [
    {
      "statementPointerTarget": "/name",
      "motivation": "transformation",
      "description": "Transliterated from Ukranian to Latin characters using...",
      "transformedContent": "TOVARYSTVO Z OBMEZHENOYU VIDPOVIDALʹNISTYU 'NAUKOVO-VYROBNYCHA FIRMA 'MARCH-A''"
    },
    {
      "statementPointerTarget": "/addresses/0",
      "motivation": "transformation",
      "description": "Transliterated from Ukranian to Latin characters using...",
      "transformedContent": "T01021, m.Kyyiv, Pechersʹkyy rayon, VULYTSYA M.HRUSHEVSʹKOHO, budynok 28/2, nezhyle prymishchennya 43"
    }
  ],
  "source": {
    "type": ["officialRegister", "thirdParty"],
    "description": "Open Ownership Register, using data from the Ukraine United State Register and OpenCorporates",
    "url": "https://register.openownership.org/entities/5a7b038b9dfc3fae18417a58?transliterated=true"
  },
  "publicationDetails": {
    "publicationDate": "2018-10-02",
    "bodsVersion": "0.2",
    "publisher": {
      "name": "МІНІСТЕРСТВО ЮСТИЦІЇ УКРАЇНИ"
    }
  }
}

=== openownership/data-standard/examples/flat-serialisation/gb-coh-entity-statement.json
{
  "statementID": "1dc0e987-5c57-4a1c-b3ad-61353b66a9b7",
  "statementType": "entityStatement",
  "entityType": "registeredEntity",
  "isComponent": false,
  "statementDate": "2017-11-18",
  "name": "CHRINON LTD",
  "foundingDate": "2010-11-18",
  "identifiers": [
    {
      "scheme": "GB-COH",
      "id": "07444723"
    }
  ],
  "publicationDetails": {
    "publicationDate": "2017-11-18",
    "bodsVersion": "0.2",
    "publisher": {
      "name": "CHRINON LTD"
    }
  }
}

=== openownership/data-standard/examples/workshop/modelling-bods-data/renco-energy-ltd-entity-statement.json
{
  "statementID": "155009d4-9295-4845-9079-b6b69a17e185",
  "statementType": "entityStatement",
  "entityType": "registeredEntity",
  "isComponent": false,
  "name": "RENCO Energy Ltd",
  "identifiers": [
    {
      "scheme": "XE-DI-CR",
      "id": "56462342"
    }
  ],
  "publicationDetails": {
    "publicationDate": "2017-12-01",
    "bodsVersion": "0.2",
    "publisher": {
      "name": "XXXXXXXXX"
    }
  }
}
