=== openownership/data-standard/schema/ownership-or-control-statement.json
{
  "id": "ownership-or-control-statement.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "0.1",
  "title": "Ownership or control Statement",
  "description": "An ownership or control statement is made up of an entity, an interested party (a reference to an entity, natural person, arrangement or trust), details of the interest and provenance information for the statement.",
  "type": "object",
  "properties": {
    "statementID": {
      "$ref": "components.json#/definitions/ID"
    },
    "statementType": {
      "title": "Statement type",
      "description": "This should always be set to `ownershipOrControlStatement`.",
      "type": "string",
      "enum": [
        "ownershipOrControlStatement"
      ]
    },
    "statementDate": {
      "$ref": "components.json#/definitions/StatementDate"
    },
    "isComponent": {
      "title": "Is component",
      "description": "Does this Ownership-or-control Statement represent a component of a wider indirect ownership-or-control relationship? Where `isComponent` is 'true': (1) the `statementID` of this secondary Ownership-or-control Statement MUST be an element in the `componentStatementIDs` array of that primary Ownership-or-control Statement, (2) this Ownership-or-control Statement MUST come before that primary Ownership-or-control Statement in a BODS package or stream, (3) the replacement of this Ownership-or-control Statement SHOULD be considered when replacing the primary Ownership-or-control Statement, and (4) the primary Ownership-or-control Statement MUST have a `isComponent` value of 'false'. Where `isComponent` is 'false', this Ownership-or-control Statement is the primary declaration of the relationship between the `subject` and the `interestedParty`.",
      "type": "boolean"
    },
    "componentStatementIDs": {
      "title": "Component statement IDs",
      "description": "The identifiers of all component statements that provide detail about the indirect relationship between this Statement's `subject` and `interestedParty`. If this Ownership-or-control Statement has components, it MUST itself have a `isComponent` value of 'false'.",
      "type": "array",
      "items": {
        "$ref": "components.json#/definitions/ID"
      }
    },
    "subject": {
      "title": "Subject",
      "description": "The subject of an ownership or control relationship.",
      "type": "object",
      "properties": {
        "describedByEntityStatement": {
          "title": "Described by entity statement",
          "description": "Provide the identifier of the statement which describes the entity that the subject of an ownership or control interest.",
          "type": "string"
        }
      },
      "required": [
        "describedByEntityStatement"
      ]
    },
    "interestedParty": {
      "$ref": "#/definitions/InterestedParty"
    },
    "interests": {
      "title": "Interests",
      "description": "A description of the interests held by the interestedParty covered by this statement in the entity covered by this statement.",
      "type": "array",
      "items": {
        "$ref": "components.json#/definitions/Interest"
      }
    },
    "publicationDetails": {
      "title": "Publication details",
      "description": "Information concerning the original publication of this statement.",
      "$ref": "components.json#/definitions/PublicationDetails"
    },
    "source": {
      "title": "Source",
      "description": "The source of the information that links the entity and the interested party, or that supports a null statement.",
      "$ref": "components.json#/definitions/Source"
    },
    "annotations": {
      "title": "Annotations",
      "description": "Annotations about this statement or parts of this statement",
      "type": "array",
      "items": {
        "$ref": "components.json#/definitions/Annotation"
      }
    },
    "replacesStatements": {
      "$ref": "components.json#/definitions/ReplacesStatements"
    }
  },
  "required": [
    "statementID",
    "statementType",
    "isComponent",
    "subject",
    "interestedParty",
    "publicationDetails"
  ],
  "definitions": {
    "InterestedParty": {
      "title": "Interested party",
      "description": "The interested party has some level of ownership or control over the entity referenced in this ownership or control statement. This should be described with reference to either an entity statement or person statement, or, where the interested party is unknown, details of why. ",
      "type": "object",
      "properties": {
        "describedByEntityStatement": {
          "title": "Described by entity statement",
          "description": "A reference to a statement describing a registered entity, trust or arrangement that has an ownership or control interest in the subject of this statement. An entityStatement should be used when the direct interests to be described represents known control or ownership by anyone other than a natural person.",
          "type": "string"
        },
        "describedByPersonStatement": {
          "title": "Described by person statement",
          "description": "A reference to a statement describing a natural person who has an ownership or control interest in the subject of this statement.",
          "type": "string"
        },
        "unspecified": {
          "title": "Unspecified or unknown ownership and control",
          "description": "When confirmation has been provided that no interested party exists, where ownership and control information does not need to be provided, or where details of ownership and control are unknown, a `reason` MUST be given. Where an unknown entity is the `subject` of further ownershipOrControlStatements in the same structure, or where there is a natural person with ownership or control but their name or details are not known or cannot be disclosed for some reason, `unspecified` should not be used, but instead a reference to a `personStatement` or `entityStatement` should be provided but identifying details MAY be left blank.",
          "type": "object",
          "properties": {
            "reason": {
              "title": "Reason",
              "description": "The reason that an interested party cannot be specified. From the [unspecifiedReason codelist](#unspecifiedreason).",
              "type": "string",
              "enum": [
                "no-beneficial-owners",
                "subject-unable-to-confirm-or-identify-beneficial-owner",
                "interested-party-has-not-provided-information",
                "subject-exempt-from-disclosure",
                "interested-party-exempt-from-disclosure",
                "unknown",
                "information-unknown-to-publisher"
              ],
              "codelist": "unspecifiedReason.csv",
              "openCodelist": false
            },
            "description": {
              "title": "Description",
              "description": "Any supporting information about the absence of a confirmed beneficial owner. This field may be used to provide set phrases from a source system, or for a free-text explanation.",
              "type": "string"
            }
          },
          "required": [
            "reason"
          ]
        }
      }
    }
  }
}

=== openownership/data-standard/examples/workshop/modelling-bods-data/ren-consulting-limited-natalie-coleman.json
{
  "statementID": "487e303b-f5be-4dc2-bcae-b0803546fa29",
  "statementType": "ownershipOrControlStatement",
  "isComponent": false,
  "subject": {
    "describedByEntityStatement": "3ff64336-9d26-49da-b0ce-f4685c6af139"
  },
  "interestedParty": {
    "describedByPersonStatement": "5eb1e15c-fd25-40c7-8a75-246c79654185"
  },
  "interests": [
    {
      "type": "shareholding",
      "interestLevel": "direct",
      "share": {
        "minimum": 25,
        "maximum": 50
      },
      "startDate": "2016-07-07"
    },
    {
      "type": "voting-rights",
      "interestLevel": "direct",
      "share": {
        "minimum": 25,
        "maximum": 50
      },
      "startDate": "2016-07-07"
    }
  ],
  "publicationDetails": {
    "publicationDate": "2017-12-01",
    "bodsVersion": "0.2",
    "publisher": {
      "name": "XXXXXXXXX"
    }
  }
}

=== openownership/data-standard/examples/workshop/modelling-bods-data/renco-energy-ltd-roberto-lopez.json
{
  "statementID": "4a0e93d8-20da-4dae-b38d-eef57490037e",
  "statementType": "ownershipOrControlStatement",
  "isComponent": false,
  "subject": {
    "describedByEntityStatement": "309523dc-8bdc-48a6-bca5-bdd3c879db65"
  },
  "interests": [
    {
      "type": "shareholding",
      "interestLevel": "direct",
      "share": {
        "exact": 25
      },
      "startDate": "2016-07-07"
    },
    {
      "type": "voting-rights",
      "interestLevel": "direct",
      "share": {
        "exact": 25
      },
      "startDate": "2016-07-07"
    }
  ],
  "interestedParty": {
    "describedByPersonStatement": "e5027662-b2bf-4a55-8319-1e4ff1c7e6a2"
  },
  "publicationDetails": {
    "publicationDate": "2017-12-01",
    "bodsVersion": "0.2",
    "publisher": {
      "name": "XXXXXXXXX"
    }
  }
}
