=== openownership/data-standard/schema/statement.json
{
  "$id": "statement.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "version": "0.4",
  "type": "object",
  "properties": {
    "statementId": {
      "title": "Statement Identifier",
      "description": "A persistent globally unique identifier for this statement.",
      "type": "string",
      "minLength": 32,
      "maxLength": 64
    },
    "statementDate": {
      "title": "Statement date",
      "description": "The date (optionally including time) on which this statement was declared by the source.",
      "type": "string",
      "anyOf": [
        {
          "format": "date"
        },
        {
          "format": "date-time"
        }
      ]
    },
    "annotations": {
      "title": "Annotations",
      "description": "Annotations about this statement or parts of this statement",
      "type": "array",
      "items": {
        "$ref": "components.json#/$defs/Annotation"
      }
    },
    "publicationDetails": {
      "title": "Publication Details",
      "description": "Information concerning the publication of this statement.",
      "type": "object",
      "properties": {
        "publicationDate": {
          "title": "Publication date",
          "description": "The date on which this statement was published, in YYYY-MM-DDTHH:MM:SS or YYYY-MM-DD format.",
          "type": "string",
          "anyOf": [
            {
              "format": "date"
            },
            {
              "format": "date-time"
            }
          ]
        },
        "bodsVersion": {
          "title": "BODS version",
          "description": "The version of the Beneficial Ownership Data Standard to which this statement conforms, expressed as major.minor. For example: 0.2 or 1.0.",
          "type": "string",
          "pattern": "^(\\d+\\.)(\\d+)$"
        },
        "license": {
          "title": "License URL",
          "description": "A link to the license that applies to this statement. The canonical URI of the license SHOULD be used. Publishers are encouraged to use a Public Domain Dedication or Open Definition Conformant (http://opendefinition.org/licenses/) license.",
          "type": "string",
          "format": "uri"
        },
        "publisher": {
          "title": "Publisher",
          "description": "Details of the organisation or individual publishing this statement.",
          "$ref": "components.json#/$defs/Publisher"
        }
      },
      "required": [
        "publicationDate",
        "bodsVersion",
        "publisher"
      ]
    },
    "source": {
      "title": "Source",
      "description": "The source of information in this statement.",
      "$ref": "components.json#/$defs/Source"
    },
    "declaration": {
      "title": "Declaration (identifier)",
      "description": "An identifier or reference for a declaration within a publisherâ€™s system. Where a Statement is a claim from a particular declaration (made at a point in time by a `source` about a `declarationSubject`) this field should be used to identify the declaration.",
      "type": "string"
    },
    "declarationSubject": {
      "title": "Declaration subject",
      "description": "A `recordId` value for the subject of a beneficial ownership network (always an entity or person).",
      "type": "string"
    },
    "recordId": {
      "title": "Record identifier",
      "description": "A unique identifier for the record (within the publisher's system) to which this Statement relates. The identifier MUST represent the series of claims made about an entity, natural person or relationship by a particular source.",
      "type": "string"
    },
    "recordType": {
      "title": "Record type",
      "description": "The type of record (within the publisher's system) to which this Statement relates: entity, person, or relationship.",
      "type": "string",
      "enum": [
        "entity",
        "person",
        "relationship"
      ]
    },
    "recordStatus": {
      "title": "Record status",
      "description": "The lifecycle status of the record (within the publisher's system ) to which this Statement relates, using the recordStatus codelist.",
      "type": "string",
      "enum": [
        "new",
        "updated",
        "closed"
      ]
    },
    "recordDetails": {
      "title": "Record details",
      "description": "The details of the entity, person or relationship as declared on the date of the statement.",
      "type": "object"
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "entity"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "entity-record.json"
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "person"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "person-record.json"
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "relationship"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "relationship-record.json"
          }
        }
      }
    }
  ],
  "required": [
    "statementId",
    "declarationSubject",
    "recordId",
    "recordType",
    "recordDetails"
  ]
}

=== openownership/data-standard/tests/data/valid-statements/Repex_deletion.json
[
    {
        "source": {
            "assertedBy": [
                {
                    "name": "GLEIF"
                }
            ],
            "url": "https://goldencopy.gleif.org/storage/golden-copy-files/2024/06/06/940025/20240606-0000-gleif-goldencopy-repex-golden-copy.csv.zip"
        },
        "statementDate": "2024-06-06",
        "annotations": [
            {
                "motivation": "commenting",
                "description": "LEI Registration Status: ISSUED",
                "statementPointerTarget": "/",
                "creationDate": "2024-08-12",
                "createdBy": {
                    "name": "Open Ownership",
                    "uri": "https://www.openownership.org"
                }
            }
        ],
        "publicationDetails": {
            "publicationDate": "2024-08-12",
            "bodsVersion": "0.4",
            "license": "https://creativecommons.org/publicdomain/zero/1.0/",
            "publisher": {
                "name": "Open Ownership",
                "url": "https://www.openownership.org"
            }
        },
        "recordId": "549300CLJRYXBPCXXV46",
        "recordStatus": "new",
        "recordType": "entity",
        "recordDetails": {
            "entityType": {
                "type": "registeredEntity"
            },
            "name": "Ewellix GmbH",
            "incorporatedInJurisdiction": {
                "name": "Germany",
                "code": "DE"
            },
            "identifiers": [
                {
                    "id": "549300CLJRYXBPCXXV46",
                    "scheme": "XI-LEI",
                    "schemeName": "Global Legal Entity Identifier Index"
                },
                {
                    "id": "HRB 7517",
                    "schemeName": "RA000336"
                }
            ],
            "addresses": [
                {
                    "type": "registered",
                    "address": "Parisstra\u00dfe 1, Schweinfurt",
                    "country": {
                        "name": "Germany",
                        "code": "DE"
                    },
                    "postCode": "97424"
                },
                {
                    "type": "business",
                    "address": "Parisstr. 1, Schweinfurt",
                    "country": {
                        "name": "Germany",
                        "code": "DE"
                    },
                    "postCode": "97424"
                }
            ],
            "foundingDate": "2017-03-17",
            "isComponent": false
        },
        "statementId": "XI-LEI-549300CLJRYXBPCXXV46-20240606",
        "declarationSubject": "549300CLJRYXBPCXXV46"
    },
    {
        "source": {
            "assertedBy": [
                {
                    "name": "GLEIF"
                }
            ],
            "url": "https://goldencopy.gleif.org/storage/golden-copy-files/2024/06/06/940025/20240606-0000-gleif-goldencopy-repex-golden-copy.csv.zip"
        },
        "statementDate": "2024-06-06",
        "publicationDetails": {
            "publicationDate": "2024-08-12",
            "bodsVersion": "0.4",
            "license": "https://creativecommons.org/publicdomain/zero/1.0/",
            "publisher": {
                "name": "Open Ownership",
                "url": "https://www.openownership.org"
            }
        },
        "recordId": "repex-d-549300CLJRYXBPCXXV46-c7db43",
        "recordStatus": "new",
        "recordType": "relationship",
        "recordDetails": {
            "subject": "549300CLJRYXBPCXXV46",
            "interestedParty": {
                "reason": "interestedPartyExemptFromDisclosure",
                "details": "Exception Reason: NON_CONSOLIDATING. The legal entity or entities are not obliged to provide consolidated accounts in relation to the entity they control."
            },
            "interests": [
                {
                    "directOrIndirect": "direct",
                    "details": "Exception Category: DIRECT_ACCOUNTING_CONSOLIDATION_PARENT",
                    "type": "otherInfluenceOrControl",
                    "beneficialOwnershipOrControl": false
                }
            ],
            "isComponent": false
        },
        "statementId": "XI-LEI-repex-d-549300CLJRYXBPCXXV46-c7db43-2024-06-06",
        "declarationSubject": "549300CLJRYXBPCXXV46"
    },
    {
        "source": {
            "assertedBy": [
                {
                    "name": "GLEIF"
                }
            ],
            "url": "https://goldencopy.gleif.org/storage/golden-copy-files/2024/06/06/940025/20240606-0000-gleif-goldencopy-repex-golden-copy.csv.zip"
        },
        "statementDate": "2024-08-07",
        "publicationDetails": {
            "publicationDate": "2024-08-12",
            "bodsVersion": "0.4",
            "license": "https://creativecommons.org/publicdomain/zero/1.0/",
            "publisher": {
                "name": "Open Ownership",
                "url": "https://www.openownership.org"
            }
        },
        "annotations": [
            {
                "motivation": "commenting",
                "description": "Reporting exception deleted",
                "statementPointerTarget": "/",
                "creationDate": "2024-08-13",
                "createdBy": {
                    "name": "Open Ownership",
                    "uri": "https://www.openownership.org"
                }
            }
        ],
        "recordId": "repex-d-549300CLJRYXBPCXXV46-c7db43",
        "recordStatus": "closed",
        "recordType": "relationship",
        "recordDetails": {
            "subject": "549300CLJRYXBPCXXV46",
            "interestedParty": {
                "reason": "interestedPartyExemptFromDisclosure",
                "details": "Exception Reason: NON_CONSOLIDATING. The legal entity or entities are not obliged to provide consolidated accounts in relation to the entity they control."
            },
            "interests": [
                {
                    "directOrIndirect": "direct",
                    "details": "Exception Category: DIRECT_ACCOUNTING_CONSOLIDATION_PARENT",
                    "type": "otherInfluenceOrControl",
                    "beneficialOwnershipOrControl": false
                }
            ],
            "isComponent": false
        },
        "statementId": "XI-LEI-repex-d-549300CLJRYXBPCXXV46-c7db43-2024-08-07",
        "declarationSubject": "549300CLJRYXBPCXXV46"
    }
]

=== openownership/data-standard/tests/data/valid-statements/fermentcat_entity_identifiers_scheme.json
[
  {
    "statementId": "2f7bf9370f1254068e5e946df067d07d",
    "recordId": "ent-93c75c87ab28f889",
    "recordType": "entity",
    "declarationSubject": "ent-93c75c87ab28f889",
    "recordDetails": {
      "isComponent": false,
      "identifiers": [
        {
          "scheme": "IE-BAU"
        }
      ],
      "entityType": {
        "type": "registeredEntity"
      }
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/statementseriesinvalid6.json
[
  {
    "statementId": "1dc0e987-5c57-4a1c-b3ad-61353b66a9b7",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2020-03-04",
    "recordId": "c359f58d2977",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      }
    }
  },
  {
    "statementId": "019a93f1-e470-42e9-957b-03559861b2e2",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2021-03-04",
    "recordId": "c359f58d2977",
    "recordType": "person",
    "recordDetails": {
      "isComponent": false,
      "personType": "knownPerson"
    }
  }
]

=== openownership/data-standard/examples/valid-bods-package.json
[
  {
    "statementId": "1dc0e987-5c57-4a1c-b3ad-61353b66a9b7",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2017-11-18",
    "publicationDetails": {
      "publicationDate": "2017-11-18",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "CHRINON LTD"
      }
    },
    "recordId": "c359f58d2977",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": false,
      "entityType": "registeredEntity",
      "name": "CHRINON LTD",
      "foundingDate": "2010-11-18",
      "identifiers": [
        {
          "scheme": "GB-COH",
          "id": "07444723"
        }
      ]
    }
  },
  {
    "statementId": "019a93f1-e470-42e9-957b-03559861b2e2",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2017-11-18",
    "publicationDetails": {
      "publicationDate": "2017-11-18",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "CHRINON LTD"
      }
    },
    "recordId": "10478c6cf6de",
    "recordStatus": "new",
    "recordType": "person",
    "recordDetails": {
      "isComponent": false,
      "personType": "knownPerson",
      "nationalities": [
        {
          "code": "GB",
          "name": "United Kingdom of Great Britain and Northern Ireland (the)"
        }
      ],
      "names": [
        {
          "type": "legal",
          "fullName": "Christopher Taggart",
          "givenName": "Christopher",
          "familyName": "Taggart"
        },
        {
          "type": "alternative",
          "fullName": "Chris Taggart"
        }
      ],
      "birthDate": "1964-04",
      "addresses": [
        {
          "type": "service",
          "address": "Aston House, Cornwall Avenue, London",
          "postCode": "N3 1LF",
          "country": {
            "name": "United Kingdom",
            "code": "GB"
          }
        }
      ]
    }
  },
  {
    "statementId": "fbfd0547-d0c6-4a00-b559-5c5e91c34f5c",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2017-11-18",
    "publicationDetails": {
      "publicationDate": "2017-11-18",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "CHRINON LTD"
      }
    },
    "recordId": "93b53022ae6a",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": false,
      "subject": "c359f58d2977",
      "interestedParty": "10478c6cf6de",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "direct",
          "startDate": "2016-04-06",
          "share": {
            "exact": 100
          }
        }
      ]
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/statement_annotations_empty_transformed.json
[
    {
        "statementId": "2f7bf9370f1254068e5e946df067d07d",
        "declarationSubject": "xyz",
        "statementDate": "2017-11-18",
        "annotations": [
            {
                "statementPointerTarget": "/recordDetails/interestedParty",
                "motivation": "correcting",
                "transformedContent": ""
            }
        ],
        "recordId": "123",
        "recordType": "entity",
        "recordDetails": {
            "entityType": {
                "type": "unknownEntity"
            },
            "isComponent": false
        }
    }
]

=== openownership/data-standard/tests/data/valid-statements/Component Statement invalid2.json
[
  {
    "statementId": "8729fec1-eb01-4866-ba40-dd5525d43db8",
    "declarationSubject": "ad3f6c2fcc9e",
    "statementDate": "2018-12-17",
    "recordId": "ad3f6c2fcc9e",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      }
    }
  },
  {
    "statementId": "e2bbe3ce-f5b4-42d0-bb68-9b405e8fd6a0",
    "declarationSubject": "ad3f6c2fcc9e",
    "statementDate": "2018-12-17",
    "recordId": "d4ab89ea169a",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": true,
      "entityType": {
        "type": "registeredEntity"
      }
    }
  },
  {
    "statementId": "6b9cfb52-505a-49cb-ab02-cc856a4e5c66",
    "declarationSubject": "ad3f6c2fcc9e",
    "statementDate": "2018-12-17",
    "recordId": "c25d4d612c2c",
    "recordStatus": "new",
    "recordType": "person",
    "recordDetails": {
      "isComponent": false,
      "personType": "knownPerson"
    }
  },
  {
    "statementId": "860155d1-a4fb-4742-9735-7a7deb899075",
    "declarationSubject": "ad3f6c2fcc9e",
    "statementDate": "2018-12-17",
    "recordId": "05e81af035e4",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "d4ab89ea169a",
      "interestedParty": "c25d4d612c2c"
    }
  },
  {
    "statementId": "cdb6acc7-426e-4a7a-9410-895d556fd329",
    "declarationSubject": "ad3f6c2fcc9e",
    "statementDate": "2018-12-17",
    "recordId": "d8d75ccf40e4",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": false,
      "subject": "ad3f6c2fcc9e",
      "interestedParty": "c25d4d612c2c",
      "componentRecords": [
        "d4ab89ea169a",
        "4cf2837bd01f",
        "05e81af035e4"
      ]
    }
  },
  {
    "statementId": "7fff3986-233f-413f-bec8-3b28c62a4a51",
    "declarationSubject": "ad3f6c2fcc9e",
    "statementDate": "2018-12-17",
    "recordId": "4cf2837bd01f",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "ad3f6c2fcc9e",
      "interestedParty": "d4ab89ea169a"
    }
  }
]

=== openownership/data-standard/examples/mutilple-indirect-ownership-2.json
[
  {
    "statementId": "c814b8ce-b120-46a0-a4ea-d58e9288e098",
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "1e049760d6c7",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Company A",
      "identifiers": [
        {
          "scheme": "GB-COH",
          "id": "XE1111"
        }
      ]
    }
  },
  {
    "statementId": "59368bde-e38d-4a95-9a6c-8ef6aec54f9f",
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "41454e3ba398",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": true,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Company B",
      "identifiers": [
        {
          "scheme": "GB-COH",
          "id": "XE2222"
        }
      ]
    }
  },
  {
    "statementId": "829ec2d1-6ecb-4ca6-874f-c9c59f2cd843",
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "6c9fd5c92201",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": true,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Company C",
      "identifiers": [
        {
          "scheme": "GB-COH",
          "id": "XE3333"
        }
      ]
    }
  },
  {
    "statementId": "78feb28a-4331-4341-b9cb-c3a695a76e63",
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "731c7a8e7601",
    "recordStatus": "new",
    "recordType": "person",
    "recordDetails": {
      "isComponent": false,
      "personType": "knownPerson",
      "names": [
        {
          "type": "legal",
          "fullName": "Person 1"
        }
      ],
      "nationalities": [
        {
          "name": "British",
          "code": "GB"
        }
      ],
      "birthDate": "1975-11"
    }
  },
  {
    "statementId": "426507cf-e5ac-45c4-b6b0-92952a954623",
    "source": {
      "assertedBy": [
        {
          "name": "Company A"
        }
      ]
    },
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "803a942b3ec8",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "1e049760d6c7",
      "interestedParty": "41454e3ba398",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "direct",
          "beneficialOwnershipOrControl": false,
          "share": {
            "exact": 40
          },
          "startDate": "2017-11-01"
        }
      ]
    }
  },
  {
    "statementId": "3a1ba916-5f3d-4335-860d-3f7c20283c42",
    "source": {
      "assertedBy": [
        {
          "name": "Company A"
        }
      ]
    },
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "9f4256f3de2f",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "1e049760d6c7",
      "interestedParty": "6c9fd5c92201",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "direct",
          "beneficialOwnershipOrControl": false,
          "share": {
            "exact": 20
          },
          "startDate": "2017-11-01"
        }
      ]
    }
  },
  {
    "statementId": "a56a0ced-447e-420d-9a07-42dcbc960a5f",
    "source": {
      "assertedBy": [
        {
          "name": "Company A"
        }
      ]
    },
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "b8e59fa7e1a6",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "41454e3ba398",
      "interestedParty": "731c7a8e7601",
      "interests": [
        {
          "directOrIndirect": "unknown",
          "beneficialOwnershipOrControl": true
        }
      ]
    }
  },
  {
    "statementId": "337d8ba1-9d0d-4a64-bc5d-820c95a127fc",
    "source": {
      "assertedBy": [
        {
          "name": "Company A"
        }
      ]
    },
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "5a8646b55833",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "6c9fd5c92201",
      "interestedParty": "731c7a8e7601",
      "interests": [
        {
          "directOrIndirect": "unknown",
          "beneficialOwnershipOrControl": true
        }
      ]
    }
  },
  {
    "statementId": "0713bc04-13a5-49d0-aefe-0c6cc35f7d3b",
    "source": {
      "assertedBy": [
        {
          "name": "Company A"
        }
      ]
    },
    "declarationSubject": "1e049760d6c7",
    "statementDate": "2018-12-17",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "d043dcc6d88e",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": false,
      "subject": "1e049760d6c7",
      "interestedParty": "731c7a8e7601",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "indirect",
          "beneficialOwnershipOrControl": true,
          "share": {
            "exact": 60
          },
          "startDate": "2017-11-01"
        }
      ],
      "componentRecords": [
        "41454e3ba398",
        "6c9fd5c92201",
        "803a942b3ec8",
        "9f4256f3de2f",
        "b8e59fa7e1a6",
        "5a8646b55833"
      ]
    }
  }
]

=== openownership/data-standard/tests/data/v0.4/valid-statements/tecido_relationship.json
[{
    "statementId": "crxpru407636437638495407739553674232",
    "statementDate": "2019-01-20",
    "publicationDetails": {
        "publicationDate": "2019-01-31",
        "bodsVersion": "0.4",
        "license": "http://opendefinition.org/licenses/cc-zero",
        "publisher": {
            "name": "Company Register, Delaware"
        }
    },
    "recordId": "022EBEB66B",
    "recordType": "relationship",
    "recordStatus": "new",
    "source": {
        "type": ["selfDeclaration"],
        "assertedBy": [
            {
                "name": "Maria Esteves"
            }
        ]
    },
    "declaration": "bo-jtc-8755982746",
    "declarationSubject": "01B68D7633",
    "recordDetails": {
        "isComponent": false,
        "subject": "01B68D7633",
        "interestedParty": "018AF6B3EB",
        "interests": [
            {
                "type": "shareholding",
                "directOrIndirect": "direct",
                "beneficialOwnershipOrControl": true,
                "share": {
                    "exact": 100,
                    "maximum": 100,
                    "minimum": 100
                },
                "startDate": "2002-03-09"
            },
            {
                "type": "votingRights",
                "directOrIndirect": "direct",
                "beneficialOwnershipOrControl": true,
                "share": {
                    "exact": 100,
                    "maximum": 100,
                    "minimum": 100
                },
                "startDate": "2002-03-09"
            },
            {
                "type": "boardChair",
                "directOrIndirect": "direct",
                "beneficialOwnershipOrControl": true,
                "startDate": "2002-03-09"
            }
        ]
    }
}]
