=== openownership/data-standard/schema/statement.json
{
  "$id": "statement.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "version": "0.4",
  "type": "object",
  "properties": {
    "statementId": {
      "title": "Statement Identifier",
      "description": "A persistent globally unique identifier for this statement.",
      "type": "string",
      "minLength": 32,
      "maxLength": 64
    },
    "statementDate": {
      "title": "Statement date",
      "description": "The date (optionally including time) on which this statement was declared by the source.",
      "type": "string",
      "anyOf": [
        {
          "format": "date"
        },
        {
          "format": "date-time"
        }
      ]
    },
    "annotations": {
      "title": "Annotations",
      "description": "Annotations about this statement or parts of this statement",
      "type": "array",
      "items": {
        "$ref": "components.json#/$defs/Annotation"
      }
    },
    "publicationDetails": {
      "title": "Publication Details",
      "description": "Information concerning the publication of this statement.",
      "type": "object",
      "properties": {
        "publicationDate": {
          "title": "Publication date",
          "description": "The date on which this statement was published, in YYYY-MM-DDTHH:MM:SS or YYYY-MM-DD format.",
          "type": "string",
          "anyOf": [
            {
              "format": "date"
            },
            {
              "format": "date-time"
            }
          ]
        },
        "bodsVersion": {
          "title": "BODS version",
          "description": "The version of the Beneficial Ownership Data Standard to which this statement conforms, expressed as major.minor. For example: 0.2 or 1.0.",
          "type": "string",
          "pattern": "^(\\d+\\.)(\\d+)$"
        },
        "license": {
          "title": "License URL",
          "description": "A link to the license that applies to this statement. The canonical URI of the license SHOULD be used. Publishers are encouraged to use a Public Domain Dedication or Open Definition Conformant (http://opendefinition.org/licenses/) license.",
          "type": "string",
          "format": "uri"
        },
        "publisher": {
          "title": "Publisher",
          "description": "Details of the organisation or individual publishing this statement.",
          "$ref": "components.json#/$defs/Publisher"
        }
      },
      "required": [
        "publicationDate",
        "bodsVersion",
        "publisher"
      ]
    },
    "source": {
      "title": "Source",
      "description": "The source of information in this statement.",
      "$ref": "components.json#/$defs/Source"
    },
    "declaration": {
      "title": "Declaration (identifier)",
      "description": "An identifier or reference for a declaration within a publisherâ€™s system. Where a Statement is a claim from a particular declaration (made at a point in time by a `source` about a `declarationSubject`) this field should be used to identify the declaration.",
      "type": "string"
    },
    "declarationSubject": {
      "title": "Declaration subject",
      "description": "A `recordId` value for the subject of a beneficial ownership network (always an entity or person).",
      "type": "string"
    },
    "recordId": {
      "title": "Record identifier",
      "description": "A unique identifier for the record (within the publisher's system) to which this Statement relates. The identifier MUST represent the series of claims made about an entity, natural person or relationship by a particular source.",
      "type": "string"
    },
    "recordType": {
      "title": "Record type",
      "description": "The type of record (within the publisher's system) to which this Statement relates: entity, person, or relationship.",
      "type": "string",
      "enum": [
        "entity",
        "person",
        "relationship"
      ]
    },
    "recordStatus": {
      "title": "Record status",
      "description": "The lifecycle status of the record (within the publisher's system ) to which this Statement relates, using the recordStatus codelist.",
      "type": "string",
      "enum": [
        "new",
        "updated",
        "closed"
      ]
    },
    "recordDetails": {
      "title": "Record details",
      "description": "The details of the entity, person or relationship as declared on the date of the statement.",
      "type": "object"
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "entity"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "entity-record.json"
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "person"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "person-record.json"
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "relationship"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "relationship-record.json"
          }
        }
      }
    }
  ],
  "required": [
    "statementId",
    "declarationSubject",
    "recordId",
    "recordType",
    "recordDetails"
  ]
}

=== openownership/data-standard/tests/data/valid-statements/statement_annotations_createdBy.json
[
  {
    "statementId": "2f7bf9370f1254068e5e946df067d07d",
    "declarationSubject": "xyz",
    "statementDate": "2017-11-18",
    "annotations": [
      {
        "statementPointerTarget": "/recordDetails/interestedParty",
        "motivation": "identifying",
        "createdBy": {
          "name": "Joe Harris"
        }
      }
    ],
    "recordId": "123",
    "recordType": "entity",
    "recordDetails": {
      "entityType": {
        "type": "unknownEntity"
      },
      "isComponent": false
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/relationship_subject_unspecified_object.json
[
    {
        "statementId": "9d167324c416bbfd37fe5c1a1b2afa95",
        "recordId": "rel-b05e7c91e0a04e4f",
        "recordType": "relationship",
        "declarationSubject": "ent-93c75c87ab28f889",
        "statementDate": "2017-11-18",
        "recordDetails": {
            "isComponent": false,
            "subject": {
                "reason": "subjectExemptFromDisclosure"
            },
            "interestedParty": "per-5faa4103dee78621"
        }
    }
]

=== openownership/data-standard/tests/data/valid-statements/entity_2.json
[
  {
    "statementId": "crxpru319949212398855320030147004728",
    "statementDate": "2019-01-20",
    "publicationDetails": {
      "publicationDate": "2019-01-31",
      "bodsVersion": "0.4",
      "license": "http://opendefinition.org/licenses/cc-zero",
      "publisher": {
        "name": "Company Register, Delaware"
      }
    },
    "recordId": "01B68D7633",
    "recordType": "entity",
    "recordStatus": "new",
    "source": {
      "type": [
        "selfDeclaration"
      ],
      "assertedBy": [
        {
          "name": "Maria Esteves"
        }
      ]
    },
    "declaration": "bo-jtc-8755982746",
    "declarationSubject": "01B68D7633",
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Tecido Ltd",
      "jurisdiction": {
        "name": "Delaware",
        "code": "US-DE"
      },
      "foundingDate": "2002-03-09",
      "identifiers": [
        {
          "id": "758355",
          "schemeName": "Company Registry, Delaware. Company number"
        }
      ]
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/entity.json
[
  {
    "statementId": "2f7bf9370f1254068e5e946df067d07d",
    "statementDate": "2021-09-11T16:15:08Z",
    "publicationDetails": {
      "publicationDate": "2021-09-11T00:00:00+00:00",
      "bodsVersion": "0.4",
      "license": "http://opendefinition.org/licenses/cc-zero",
      "publisher": {
        "name": "Irish Business Authority"
      }
    },
    "recordId": "ent-93c75c87ab28f889",
    "recordType": "entity",
    "recordStatus": "updated",
    "declarationSubject": "ent-93c75c87ab28f889",
    "source": {
      "assertedBy": [
        {
          "name": "Mary Walsh"
        }
      ]
    },
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Fermentcat Ltd",
      "jurisdiction": {
        "code": "IE",
        "name": "Ireland"
      },
      "foundingDate": "2019-09-11",
      "publicListing": {
        "hasPublicListing": false
      },
      "identifiers": [
        {
          "id": "434151",
          "scheme": "IE-BAU",
          "schemeName": "Irish Business Authority "
        }
      ],
      "addresses": [
        {
          "type": "registered",
          "address": "53 Killard, Kilteragh, Dooradoyle, Co. Limerick ",
          "postCode": "V94 V3VT",
          "country": {
            "name": "Ireland",
            "code": "IE"
          }
        }
      ]
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/source_retrieved_at_valid2.json
[
  {
    "statementId": "1dc0e987-5c57-4a1c-b3ad-61353b66a9b7",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2020-03-04",
    "recordId": "c359f58d2977",
    "recordType": "entity",
    "source": {
      "retrievedAt": "2017-01-02T01:01:00Z"
    },
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      }
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/json_pointer_invalid2.json
[
  {
    "statementId": "019a93f1-e470-42e9-957b-03559861b2e2",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2020-03-04",
    "recordId": "10478c6cf6de",
    "recordType": "person",
    "annotations":[
      {
        "statementPointerTarget": "statementId"
      }
    ],
    "recordDetails": {
      "isComponent": false,
      "personType": "knownPerson"
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/relationship_subject.json
[
    {
        "statementId": "9d167324c416bbfd37fe5c1a1b2afa95",
        "recordId": "rel-b05e7c91e0a04e4f",
        "recordType": "relationship",
        "declarationSubject": "ent-93c75c87ab28f889",
        "statementDate": "2017-11-18",
        "recordDetails": {
            "isComponent": false,
            "subject": "ent-93c75c87ab28f889",
            "interestedParty": "per-5faa4103dee78621"
        }
    }
]

=== openownership/data-standard/examples/bods-package-fi-soe.json
[
  {
    "statementId": "xregi-es-00002247037980570744606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "19f1c5afe9d7",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Gasgrid Finland Oy",
      "jurisdiction": {
        "name": "Finland",
        "code": "FI"
      },
      "identifiers": [
        {
          "id": "3007894-1",
          "scheme": "FI-PRO"
        }
      ],
      "foundingDate": "2020-01-01"
    }
  },
  {
    "statementId": "xregi-es-00008546493688880044606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "0199c515a699",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": true,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Suomen Kaasuverkko Oy",
      "jurisdiction": {
        "name": "Finland",
        "code": "FI"
      },
      "identifiers": [
        {
          "id": "3010424-9",
          "scheme": "FI-PRO"
        }
      ],
      "foundingDate": "2020-01-01"
    }
  },
  {
    "statementId": "xregi-es-00001461827397290944606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "7ff95ba3682c",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": true,
      "entityType": {
        "type": "stateBody",
        "subtype": "governmentDepartment",
        "details": "ministerio"
      },
      "name": "Valtiovarainministerio",
      "alternateNames": [
        "Finansministeriet"
      ],
      "jurisdiction": {
        "name": "Finland",
        "code": "FI"
      }
    }
  },
  {
    "statementId": "xregi-es-00000683117111100044606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "05ce06ec97b1",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "state"
      },
      "name": "Suomen tasavalta",
      "alternateNames": [
        "Republic of Finland"
      ],
      "jurisdiction": {
        "name": "Finland",
        "code": "FI"
      }
    }
  },
  {
    "statementId": "xregi-oocs-00000384456595684844606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "87ed6d1daf8f",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "subject": "19f1c5afe9d7",
      "interestedParty": "0199c515a699",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "direct",
          "beneficialOwnershipOrControl": false,
          "share": {
            "exact": 76.5
          },
          "startDate": "2020-01-01"
        }
      ],
      "isComponent": true
    }
  },
  {
    "statementId": "xregi-oocs-00004319992040145444606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "e34164e75ac3",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "subject": "0199c515a699",
      "interestedParty": "7ff95ba3682c",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "direct",
          "beneficialOwnershipOrControl": false,
          "share": {
            "exact": 100
          },
          "startDate": "2020-01-01"
        }
      ],
      "isComponent": true
    }
  },
  {
    "statementId": "xregi-oocs-00007980570744606044606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "10643ee6d6fa",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "subject": "19f1c5afe9d7",
      "interestedParty": "7ff95ba3682c",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "direct",
          "beneficialOwnershipOrControl": false,
          "share": {
            "exact": 23.5
          },
          "startDate": "2020-01-01"
        }
      ],
      "isComponent": true
    }
  },
  {
    "statementId": "xregi-oocs-00000137020039066644606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "324d0f570675",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "subject": "7ff95ba3682c",
      "interestedParty": "05ce06ec97b1",
      "interests": [
        {
          "type": "otherInfluenceOrControl",
          "directOrIndirect": "direct",
          "beneficialOwnershipOrControl": false
        }
      ],
      "isComponent": true
    }
  },
  {
    "statementId": "xregi-oocs-00005576684893527244606",
    "source": {
      "type": [
        "primaryResearch"
      ]
    },
    "declarationSubject": "19f1c5afe9d7",
    "statementDate": "2022-02-14",
    "publicationDetails": {
      "publicationDate": "2022-04-01",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/licenses/by/2.0/legalcode",
      "publisher": {
        "name": "X Register",
        "url": "http://www.register.example"
      }
    },
    "recordId": "e8ddaee2a7a4",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "subject": "19f1c5afe9d7",
      "interestedParty": "05ce06ec97b1",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "indirect",
          "beneficialOwnershipOrControl": false,
          "share": {
            "exact": 100
          },
          "startDate": "2020-01-01"
        }
      ],
      "isComponent": false,
      "componentRecords": [
        "0199c515a699",
        "7ff95ba3682c",
        "87ed6d1daf8f",
        "e34164e75ac3",
        "10643ee6d6fa",
        "324d0f570675"
      ]
    }
  }
]
