=== openownership/data-standard/schema/statement.json
{
  "$id": "statement.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "version": "0.4",
  "type": "object",
  "properties": {
    "statementId": {
      "title": "Statement Identifier",
      "description": "A persistent globally unique identifier for this statement.",
      "type": "string",
      "minLength": 32,
      "maxLength": 64
    },
    "statementDate": {
      "title": "Statement date",
      "description": "The date (optionally including time) on which this statement was declared by the source.",
      "type": "string",
      "anyOf": [
        {
          "format": "date"
        },
        {
          "format": "date-time"
        }
      ]
    },
    "annotations": {
      "title": "Annotations",
      "description": "Annotations about this statement or parts of this statement",
      "type": "array",
      "items": {
        "$ref": "components.json#/$defs/Annotation"
      }
    },
    "publicationDetails": {
      "title": "Publication Details",
      "description": "Information concerning the publication of this statement.",
      "type": "object",
      "properties": {
        "publicationDate": {
          "title": "Publication date",
          "description": "The date on which this statement was published, in YYYY-MM-DDTHH:MM:SS or YYYY-MM-DD format.",
          "type": "string",
          "anyOf": [
            {
              "format": "date"
            },
            {
              "format": "date-time"
            }
          ]
        },
        "bodsVersion": {
          "title": "BODS version",
          "description": "The version of the Beneficial Ownership Data Standard to which this statement conforms, expressed as major.minor. For example: 0.2 or 1.0.",
          "type": "string",
          "pattern": "^(\\d+\\.)(\\d+)$"
        },
        "license": {
          "title": "License URL",
          "description": "A link to the license that applies to this statement. The canonical URI of the license SHOULD be used. Publishers are encouraged to use a Public Domain Dedication or Open Definition Conformant (http://opendefinition.org/licenses/) license.",
          "type": "string",
          "format": "uri"
        },
        "publisher": {
          "title": "Publisher",
          "description": "Details of the organisation or individual publishing this statement.",
          "$ref": "components.json#/$defs/Publisher"
        }
      },
      "required": [
        "publicationDate",
        "bodsVersion",
        "publisher"
      ]
    },
    "source": {
      "title": "Source",
      "description": "The source of information in this statement.",
      "$ref": "components.json#/$defs/Source"
    },
    "declaration": {
      "title": "Declaration (identifier)",
      "description": "An identifier or reference for a declaration within a publisherâ€™s system. Where a Statement is a claim from a particular declaration (made at a point in time by a `source` about a `declarationSubject`) this field should be used to identify the declaration.",
      "type": "string"
    },
    "declarationSubject": {
      "title": "Declaration subject",
      "description": "A `recordId` value for the subject of a beneficial ownership network (always an entity or person).",
      "type": "string"
    },
    "recordId": {
      "title": "Record identifier",
      "description": "A unique identifier for the record (within the publisher's system) to which this Statement relates. The identifier MUST represent the series of claims made about an entity, natural person or relationship by a particular source.",
      "type": "string"
    },
    "recordType": {
      "title": "Record type",
      "description": "The type of record (within the publisher's system) to which this Statement relates: entity, person, or relationship.",
      "type": "string",
      "enum": [
        "entity",
        "person",
        "relationship"
      ]
    },
    "recordStatus": {
      "title": "Record status",
      "description": "The lifecycle status of the record (within the publisher's system ) to which this Statement relates, using the recordStatus codelist.",
      "type": "string",
      "enum": [
        "new",
        "updated",
        "closed"
      ]
    },
    "recordDetails": {
      "title": "Record details",
      "description": "The details of the entity, person or relationship as declared on the date of the statement.",
      "type": "object"
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "entity"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "entity-record.json"
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "person"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "person-record.json"
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "recordType": {
            "const": "relationship"
          }
        }
      },
      "then": {
        "properties": {
          "recordDetails": {
            "$ref": "relationship-record.json"
          }
        }
      }
    }
  ],
  "required": [
    "statementId",
    "declarationSubject",
    "recordId",
    "recordType",
    "recordDetails"
  ]
}

=== openownership/data-standard/tests/data/valid-statements/statement_annotations_description.json
[
    {
        "statementId": "2f7bf9370f1254068e5e946df067d07d",
        "declarationSubject": "xyz",
        "statementDate": "2017-11-18",
        "annotations": [
            {
                "statementPointerTarget": "/recordDetails/interestedParty",
                "motivation": "identifying",
                "description": "The interested party is a British MP and, at the time this statement was made, the Secretary of State for Health and Social Care."
            }
        ],
        "recordId": "123",
        "recordType": "entity",
        "recordDetails": {
            "entityType": {
                "type": "unknownEntity"
            },
            "isComponent": false
        }
    }
]

=== openownership/data-standard/tests/data/valid-statements/fermentcat_entity_identifiers_scheme_name.json
[
  {
    "statementId": "2f7bf9370f1254068e5e946df067d07d",
    "recordId": "ent-93c75c87ab28f889",
    "recordType": "entity",
    "declarationSubject": "ent-93c75c87ab28f889",
    "recordDetails": {
      "isComponent": false,
      "identifiers": [
        {
          "schemeName": "Irish Business Authority "
        }
      ],
      "entityType": {
        "type": "registeredEntity"
      }
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/no_known_person_exception.json
[
  {
    "statementId": "7b97861e-5470-e539-c965-c5dff5f5a17d",
    "source": {
      "type": [
        "officialRegister",
        "verified"
      ],
      "description": "GLEIF"
    },
    "statementDate": "2023-10-02",
    "annotations": [
      {
        "motivation": "commenting",
        "description": "LEI Registration Status: ISSUED",
        "statementPointerTarget": "/",
        "creationDate": "2024-08-12",
        "createdBy": {
          "name": "Open Ownership",
          "uri": "https://www.openownership.org"
        }
      }
    ],
    "publicationDetails": {
      "publicationDate": "2024-08-12",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/publicdomain/zero/1.0/",
      "publisher": {
        "name": "Open Ownership",
        "url": "https://www.openownership.org"
      }
    },
    "recordId": "254900UCWGL6FFMOVH42",
    "recordStatus": "new",
    "recordType": "entity",
    "declarationSubject": "254900UCWGL6FFMOVH42",
    "recordDetails": {
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Rescue Lane Properties, LLC",
      "incorporatedInJurisdiction": {
        "name": "Pennsylvania, United States",
        "code": "US-PA"
      },
      "identifiers": [
        {
          "id": "254900UCWGL6FFMOVH42",
          "scheme": "XI-LEI",
          "schemeName": "Global Legal Entity Identifier Index"
        },
        {
          "id": "13583179",
          "schemeName": "RA000632"
        }
      ],
      "addresses": [
        {
          "type": "registered",
          "address": "4668 Breezyview Road, Columbia",
          "country": {
            "name": "United States of America",
            "code": "US"
          },
          "postCode": "17512"
        },
        {
          "type": "business",
          "address": "4668 Breezyview Road, Columbia",
          "country": {
            "name": "United States of America",
            "code": "US"
          },
          "postCode": "17512"
        }
      ],
      "foundingDate": "2023-09-13"
    }
  },
  {
    "statementId": "1fe05b54-29f8-e9c5-e8cd-6a0093dfe609",
    "source": {
      "type": [
        "officialRegister"
      ],
      "description": "GLEIF"
    },
    "statementDate": "2024-06-06",
    "annotations": [
      {
        "motivation": "commenting",
        "description": "The nature of this interest is unknown",
        "statementPointerTarget": "/interests/0/type",
        "creationDate": "2024-08-12",
        "createdBy": {
          "name": "Open Ownership",
          "uri": "https://www.openownership.org"
        }
      },
      {
        "motivation": "commenting",
        "description": "This statement was created due to a NO_KNOWN_PERSON GLEIF Reporting Exception for 254900UCWGL6FFMOVH42",
        "statementPointerTarget": "/",
        "creationDate": "2024-08-12",
        "createdBy": {
          "name": "Open Ownership",
          "uri": "https://www.openownership.org"
        }
      }
    ],
    "publicationDetails": {
      "publicationDate": "2024-08-12",
      "bodsVersion": "0.4",
      "license": "https://creativecommons.org/publicdomain/zero/1.0/",
      "publisher": {
        "name": "Open Ownership",
        "url": "https://www.openownership.org"
      }
    },
    "recordId": "254900UCWGL6FFMOVH42-",
    "recordStatus": "new",
    "recordType": "relationship",
    "declarationSubject": "254900UCWGL6FFMOVH42",
    "recordDetails": {
      "subject": "59acb2f32c0d",
      "interestedParty": {
        "reason": "subjectUnableToConfirmOrIdentifyBeneficialOwner",
        "description": "Exception Reason: NO_KNOWN_PERSON"
      },
      "interests": [
        {
          "type": "otherInfluenceOrControl",
          "interestLevel": "direct",
          "beneficialOwnershipOrControl": false,
          "details": "Exception Category: DIRECT_ACCOUNTING_CONSOLIDATION_PARENT"
        }
      ]
    }
  } 
]

=== openownership/data-standard/examples/listed-company-exempt-from-disclosure.json
[
  {
    "statementId": "60bb3996-b434-4377-930b-39972c65b400",
    "source": {
      "assertedBy": [
        {
          "name": "Listed Company 17"
        }
      ]
    },
    "declarationSubject": "4c7ea3bfbe6c",
    "statementDate": "2019-05-05",
    "publicationDetails": {
      "publicationDate": "2019-06-13",
      "publisher": {
        "name": "Example Register"
      },
      "bodsVersion": "0.4"
    },
    "recordId": "4c7ea3bfbe6c",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Listed Company OS-17",
      "publicListing": {
        "hasPublicListing": true
      },
      "identifiers": [
        {
          "scheme": "GB-COH",
          "id": "XE000017"
        }
      ]
    }
  },
  {
    "statementId": "5b7273f7-6ca1-40f3-9146-646ce0f8b03e",
    "source": {
      "assertedBy": [
        {
          "name": "Listed Company 17"
        }
      ]
    },
    "declarationSubject": "4c7ea3bfbe6c",
    "statementDate": "2019-05-10",
    "publicationDetails": {
      "publicationDate": "2019-06-13",
      "publisher": {
        "name": "Example Register"
      },
      "bodsVersion": "0.4"
    },
    "recordId": "fa402c4818f9",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": false,
      "subject": "4c7ea3bfbe6c",
      "interestedParty": {
        "reason": "subjectExemptFromDisclosure",
        "description": "Exempt from disclosure as a company listed on a recognised stock exchange"
      }
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/entity_statementDate_time.json
[
  {
    "statementId": "2f7bf9370f1254068e5e946df067d07d",
    "declarationSubject": "xyz",
    "statementDate": "2020-09-11T16:30:23Z",
    "recordId": "123",
    "recordType": "entity",
    "recordDetails": {
      "entityType": {
        "type": "registeredEntity"
      },
      "isComponent": false
    }
  }
]

=== openownership/data-standard/examples/multiple-indirect-ownership.json
[
  {
    "statementId": "243e8f5b-8699-4fac-9b88-21713e973951",
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "63e3a8a8946f",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Company B",
      "identifiers": [
        {
          "scheme": "UA-EDR",
          "id": "UA-XE-02"
        }
      ]
    }
  },
  {
    "statementId": "2ba6417f-bd77-4e8c-a4c6-6d6f10315bdb",
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "92ebf964a1f6",
    "recordStatus": "new",
    "recordType": "person",
    "recordDetails": {
      "isComponent": false,
      "personType": "knownPerson",
      "names": [
        {
          "type": "legal",
          "fullName": "Person 1"
        }
      ],
      "nationalities": [
        {
          "name": "Ukrainian",
          "code": "UA"
        }
      ],
      "birthDate": "1965-10"
    }
  },
  {
    "statementId": "8a323bcd-f047-41d5-a194-205ebffedd7",
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "d177864a8b39",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": true,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Company C",
      "identifiers": [
        {
          "scheme": "GB-COH",
          "id": "GB-XE-03"
        }
      ]
    }
  },
  {
    "statementId": "e408d5c2-c41c-4b14-a43e-b0b7e9808328",
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "05fbbfb94b79",
    "recordStatus": "new",
    "recordType": "entity",
    "recordDetails": {
      "isComponent": true,
      "entityType": {
        "type": "registeredEntity"
      },
      "name": "Company D",
      "identifiers": [
        {
          "scheme": "GB-COH",
          "id": "GB-XE-04"
        }
      ]
    }
  },
  {
    "statementId": "3cfba7c7-95c9-4194-9d6b-0ce063a4d4c5",
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "40b9a74c70c4",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "63e3a8a8946f",
      "interestedParty": "d177864a8b39",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "direct",
          "beneficialOwnershipOrControl": false,
          "share": {
            "exact": 50
          },
          "startDate": "2017-11-01"
        }
      ]
    }
  },
  {
    "statementId": "ffb65ea4-fe51-46f7-b9c7-b40b375c7b56",
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "9615ef9a4a0b",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "63e3a8a8946f",
      "interestedParty": "05fbbfb94b79",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "direct",
          "beneficialOwnershipOrControl": false,
          "share": {
            "exact": 50
          },
          "startDate": "2017-11-01"
        }
      ]
    }
  },
  {
    "statementId": "a0decdf4-6b57-4dc1-ba57-42533e2d17c4",
    "source": {
      "assertedBy": [
        {
          "name": "Company B"
        },
        {
          "name": "Company C"
        }
      ]
    },
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "e351a9247e22",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "d177864a8b39",
      "interestedParty": "92ebf964a1f6",
      "interests": [
        {
          "directOrIndirect": "unknown",
          "beneficialOwnershipOrControl": true
        }
      ]
    }
  },
  {
    "statementId": "caa00429-44b2-44da-b562-1384b4cd2a85",
    "source": {
      "assertedBy": [
        {
          "name": "Company B"
        },
        {
          "name": "Company D"
        }
      ]
    },
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "721da228c733",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": true,
      "subject": "05fbbfb94b79",
      "interestedParty": "92ebf964a1f6",
      "interests": [
        {
          "directOrIndirect": "unknown",
          "beneficialOwnershipOrControl": true
        }
      ]
    }
  },
  {
    "statementId": "4ddf22ac-1936-4d5f-acf4-4e2247679379",
    "source": {
      "assertedBy": [
        {
          "name": "Company B"
        }
      ]
    },
    "declarationSubject": "63e3a8a8946f",
    "statementDate": "2019-05-16",
    "publicationDetails": {
      "publicationDate": "2017-12-01",
      "bodsVersion": "0.4",
      "publisher": {
        "name": "XXXXXXXXX"
      }
    },
    "recordId": "8af302e17272",
    "recordStatus": "new",
    "recordType": "relationship",
    "recordDetails": {
      "isComponent": false,
      "subject": "63e3a8a8946f",
      "interestedParty": "92ebf964a1f6",
      "interests": [
        {
          "type": "shareholding",
          "directOrIndirect": "indirect",
          "beneficialOwnershipOrControl": true,
          "share": {
            "exact": 60
          },
          "startDate": "2017-11-01"
        }
      ],
      "componentRecords": [
        "d177864a8b39",
        "05fbbfb94b79",
        "40b9a74c70c4",
        "9615ef9a4a0b",
        "e351a9247e22",
        "721da228c733"
      ]
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/publicationDate_valid2.json
[
  {
    "statementId": "1dc0e987-5c57-4a1c-b3ad-61353b66a9b7",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2020-03-04",
    "recordId": "c359f58d2977",
    "recordType": "entity",
    "publicationDetails":{
      "publicationDate": "2021-01-01T12:00:00Z",
      "bodsVersion": "0.4",
      "publisher":{
        "name": "test"
      }
    },
    "recordDetails": {
      "isComponent": false,
      "entityType": {
        "type": "registeredEntity"
      }
    }
  }
]

=== openownership/data-standard/tests/data/valid-statements/death_date_valid2.json
[
  {
    "statementId": "019a93f1-e470-42e9-957b-03559861b2e2",
    "declarationSubject": "c359f58d2977",
    "statementDate": "2020-03-04",
    "recordId": "10478c6cf6de",
    "recordType": "person",
    "recordDetails": {
      "isComponent": false,
      "personType": "knownPerson",
      "deathDate":"2012-09-01"
    }
  }
]
